routes/web.php
<?php
// Auth::logout();
Route::get('storage/{filename}', function ($filename)
{
    $path = storage_path('app/public/' . $filename);

    if (!File::exists($path)) {
        abort(404);
    }

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});
Auth::routes();
// verify not working!
Route::get('/verify/', ['uses' => '\App\Http\Controllers\Auth\RegisterController@showRegistrationForm', 'as' => 'verification.verify']);
Route::get('/register-social-media/{provider}', '\App\Http\Controllers\Auth\RegisterController@redirectToProvider');
Route::get('/register-social-media/{provider}/callback', '\App\Http\Controllers\Auth\RegisterController@handleProviderCallback');

Route::get('/register/', ['uses' => '\App\Http\Controllers\Auth\RegisterController@showRegistrationForm']);
Route::get('/register/{role}', ['uses' => '\App\Http\Controllers\Auth\RegisterController@index']);
Route::post('/register/member', ['uses' => '\App\Http\Controllers\Auth\RegisterController@register_member']);
Route::post('/register/beneficiary', ['uses' => '\App\Http\Controllers\Auth\RegisterController@register_beneficiary']);
Route::post('/register/uploadHands', ['uses' => '\App\Http\Controllers\Auth\RegisterController@upload_hands_pictures']);
Route::get('/', ['uses' => 'HomeController@index', 'as' => 'app.home.index']);
Route::get('/contact-us', ['uses' => 'HomeController@contact', 'as' => 'app.home.contact']);
Route::post('/contact-us', ['uses' => 'HomeController@post_contact', 'as' => 'app.home.contact']);
Route::get('/terms', ['uses' => 'HomeController@terms', 'as' => 'app.home.term']);
Route::get('/privacy', ['uses' => 'HomeController@privacy', 'as' => 'app.home.privacy']);
Route::get('/about', ['uses' => 'HomeController@about', 'as' => 'app.home.about']);
Route::get('lang/{locale}', 'LocalizationController@index');

Route::post('/categories-requirements', ['uses' => 'CategoryController@getRequirements', 'as' => 'app.category.requirements']);
 Route::group(['middleware' => 're'], function () {
});
Route::group(['middleware' => 'auth'], function () {
    Route::get('/successful-payment', ['uses' => 'PaymentController@successful', 'as' => 'app.payment.successful']);    
    // Route::get('/failed-payment', ['uses' => 'PaymentController@failed', 'as' => 'app.payment.failed']);    
    
    Route::get('/user/settings', ['uses' => 'UserController@settings', 'as' => 'app.user.setting']);
    Route::post('/user/settings', ['uses' => 'UserController@post_setting', 'as' => 'app.user.setting']);

    Route::get('/set-category', ['uses' => 'UserController@set_category_get', 'as' => 'app.user.set_category']);
    Route::post('/set-category', ['uses' => 'UserController@set_category_post', 'as' => 'app.user.set_category']);
    Route::get('/user/dashboard', ['uses' => 'UserController@dashboard', 'as' => 'app.user.dashboard']);
    Route::get('/user/orders', ['uses' => 'UserController@orders', 'as' => 'app.user.order']);
    Route::get('/user/payments', ['uses' => 'UserController@payments', 'as' => 'app.user.payment']);
    Route::get('/user/bank', ['uses' => 'UserController@bank', 'as' => 'app.user.bank']);
    Route::get('/user/portofolios', ['uses' => 'UserController@portofolios', 'as' => 'app.user.portofolio']);
    Route::resource('/user', 'UserController', ['as' => 'app']);
    Route::resource('/order', 'OrderController', ['as' => 'app']);
    Route::get('/category/filter/', ['uses' => 'CategoryController@filter', 'as' => 'app.category.filter']);
    Route::resource('/category', 'CategoryController', ['as' => 'app']);
    Route::resource('/portofolio', 'PortofolioController', ['as' => 'app']);
    Route::resource('/payment', 'PaymentController', ['as' => 'app']);
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Collection;
use Spatie\Permission\Traits\HasRoles;
use Illuminate\Support\Facades\Hash;
use App\Notifications\VerifyUser;
use Laravel\Passport\HasApiTokens;

class User extends Authenticatable
{
    use Notifiable, HasRoles, HasApiTokens;

    protected $guarded = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $with = ['country', 'skin', 'hair', 'gender', 'eye', 'resident', 'portfolios', 'accents', 'price', 'rate', 'socials', 'balance'];

    protected $appends = ['avatar_url', 'front_hand_url', 'back_hand_url', 'role', 'category_name', 'price_type'];

    public function avatar()
    {
        if(is_null($this->avatar) && !file_exists(asset('storage/'. $this->avatar)))
        {
            return asset('storage/no-avatar.png');
        }
        else
        {
            return asset('storage/'. $this->avatar);
        }
    }

    public function getCategoryNameAttribute()
    {
        if(! is_null($this->category()->first()))
        {
            return $this->category()->first()->name;
        }
        else
        {
            return null;
        }
    }

    public function getIsTravelAttribute($value)
    {
        if(is_null($value))
        {
            return __('general.notcare');
        }
        else if($value == 0)
        {
            return __('general.no');
        }
        else if($value == 1)
        {
            return __('general.yes');
        }
    }

    public function getRoleNames(): Collection
    {
        return $this->roles->pluck('display_name');
    }

    public function status()
    {
        return $this->status == 1 ? 'مفعل' : 'غير مفعل';
    }

    public function getFullNameAttribute()
    {
        return $this->fname . ' ' . $this->lname;
    }

    public function category()
    {
        return $this->belongsTo('App\Models\Category', 'user_category_id');
    }

    public function country()
    {
        return $this->belongsTo('App\Models\Country');
    }

    public function resident()
    {
        return $this->belongsTo('App\Models\Country', 'residence_country_id');
    }

    public function accents()
    {
        return $this->belongsToMany('App\Models\UserAccent', 'users_accents', 'user_id', 'accent_id');
    }

    public function price()
    {
        return $this->hasOne('App\Models\UserPrice');
    }

    public function gender()
    {
        return $this->belongsTo('App\Models\UserGender', 'user_gender_id');
    }

    public function attachments()
    {
        return $this->hasMany('App\Models\Attachment');
    }

    public function portfolios()
    {
        return $this->hasMany('App\Models\UserPortfolio');
    }

    public function rate()
    {
        return $this->hasOne('App\Models\UserRate');
    }

    public function eye()
    {
        return $this->belongsTo('App\Models\UserEyeColor', 'eye_color_id');
    }

    public function hair()
    {
        return $this->belongsTo('App\Models\UserHairColor', 'hair_color_id');
    }

    public function skin()
    {
        return $this->belongsTo('App\Models\UserSkinColor', 'skin_color_id');
    }

    public function socials()
    {
        return $this->belongsToMany('App\Models\SocialMedia', 'users_socials', 'user_id', 'social_media_id')->withPivot([
            'url'
        ]);
    }

    public function video()
    {
        return Attachment::where('type_id', 4)->where('user_id', $this->id)->first();
    }

    public function getFrontHand()
    {
        $file = Attachment::where('type_id', 2)->where('user_id', $this->id)->latest()->first();

        if(! is_null($file))
        {
            return asset('storage/' . $file->name);
        }
        return asset('storage/no-avatar.png');
    }

    public function getBackHand()
    {
        $file = Attachment::where('type_id', 3)->where('user_id', $this->id)->latest()->first();

        if(! is_null($file))
        {
            return asset('storage/' . $file->name);
        }
        return asset('storage/no-avatar.png');
    }

    public function balance()
    {
        return $this->hasOne('App\Models\Balance', 'user_id');
    }

    public function getAvatarUrlAttribute()
    {
        return url('storage/'. $this->attributes['avatar']);
    }

    public function getFrontHandUrlAttribute()
    {
        $file = Attachment::where('type_id', 2)->where('user_id', $this->id)->latest()->first();
        if(! is_null($file))
        {
            return url('storage/'. $file->name);
        }
        return null;
    }

    public function getBackHandUrlAttribute()
    {
        $file = Attachment::where('type_id', 3)->where('user_id', $this->id)->latest()->first();
        if(! is_null($file))
        {
            return url('storage/'. $file->name);
        }
        return null;
    }

    public function getRoleAttribute()
    {
        return $this->getRoleNames();
    }

    public function getPriceTypeAttribute()
    {
        if(! is_null($this->price))
        return $this->price->type->name;
    }
}

resources/views/app/user/card.blade.php
<div class="col-md-4 col-lg-3">
    <div class="widget listing-detail">
        <div class="overview widget-background-white">
            <h2>{{ __('general.personal_card')}}</h2>
            <ul>
                <li><strong>{{ __('general.name')}}</strong><span>{{ $user->fullName }}</span></li>
                <li><strong>{{ __('general.nationality')}}</strong><span>{{ $user->country->name }}</span></li>
                <li><strong>{{ __('general.residence')}}</strong><span>{{ $user->resident->name }}</span></li>			                
                <li><strong>{{ __('general.city')}}</strong><span>{{ $user->city }}</span></li>			                
                <li><strong>{{ __('general.gender')}}</strong><span>{{ $user->gender->name }}</span></li>
                @if(! is_null($user->height))
                <li><strong>{{ __('general.height')}}</strong><span>{{ $user->height }} {{ __('general.cm')}}</span></li>
                @endif
                @if(! is_null($user->weight))             
                <li><strong>{{ __('general.weight')}}</strong><span>{{ $user->weight }} {{ __('general.kg')}}</span></li>
                @endif
                @if(! is_null($user->age))		                
                <li><strong>{{ __('general.age')}}</strong><span>{{ $user->age }} {{ __('general.year')}}</span></li>
                @endif
                @if(! is_null($user->eye))		                
                <li><strong>{{ __('general.eye_color')}}</strong><span>{{ $user->eye->name }}</span></li>
                @endif
                @if(! is_null($user->skin))		                
                <li><strong>{{ __('general.skin_color')}}</strong><span>{{ $user->skin->name }}</span></li>
                @endif
                @if(! is_null($user->hair))		                
                <li><strong>{{ __('general.hair_color')}}</strong><span>{{ $user->hair->name }}</span></li>
                @endif           
                <li><strong>{{ __('general.can_travel')}}</strong><span>{{ $user->is_travel }}</span></li>                
            </ul>
        </div><!-- /.overview -->
    </div>			
</div><!-- /.col-* -->

resources/views/app/user/show.blade.php
@extends('layouts.app')
@section('title')
{{ $user->fullName }}
@endsection
@section('content')
<div class="row">
	<!-- show profile card -->
	@include('app.user.card')

	<div class="listing-detail col-md-8 col-lg-9">
		<div class="listing-user widget-background-white">
			<div class="row">
				<div class="col-md-8 col-lg-9">
					<div class="listing-user-image">
						<a href="#" style="background-image: url({{ $user->avatar() }});"></a>
					</div><!-- /.listing-user-image -->

					<div class="listing-user-title">
						<h2>{{ $user->fullName }}</h2>
						<h3>{{ $user->category->name }}</h3>
					</div><!-- /.listing-user-title -->
				</div>
				<div class="col-md-4 col-lg-3">
					<ul style="list-style-type:none; height:0px;">
					@if(! is_null($user->rate))
						<li>{{ $user->rate->rate->name }}</li>
						<li>
							@include('partials.app.stars.'. $user->rate->rate_id)
						</li>
					@endif
					</ul><!-- /.listing-row-social -->
				</div>
				<div>
					<p class="user-about">{{ $user->about }}</p>
				</div>
			</div>
		</div>

		@foreach($user->category->requirements as $requirement)
		@if(View::exists('app.user.categories_requirements.'. $requirement->id))
		@include('app.user.categories_requirements.'. $requirement->id)
		@endif
		@endforeach

		<div class="overview widget-background-white">
			<h2>{{ __('general.order_this_service')}} {{ $user->fullName }}</h2>
			<p>
				{{ __('general.interesed_in')}} {{ $user->fullName }} {{ __('general.services')}}
			</p>
			
			<form method="POST" action="{{ route('app.order.store') }}">
				@csrf
				<div class="row">
					<div class="col-sm-12">
						<div class="form-group">
							<label>{{ __('general.want_to_say')}}</label>
							{!! Form::textarea('message', null, ['class' => 'form-control', 'rows' => 5, 'v-model' => 'message']) !!}
						</div><!-- /.form-group -->
					</div><!-- /.col-* -->

					<input type="hidden" name="beneficiary_id" value="{{ $user->id }}" />

					<div class="col-sm-12">
						<div class="form-group-btn">
							<button class="btn btn-primary pull-right">{{ __('general.send_order')}}</button>
						</div><!-- /.form-group-btn -->
					</div><!-- /.col-* -->					
				</div><!-- /.row -->
			</form>
		</div>

		@if(! is_null($similar_users)) 
		@include('app.user.show.similar_users', $similar_users)
		@endif
	</div>
	<!-- end user -->
</div>
@endsection