routes/web.php
<?php
// Auth::logout();
Route::get('storage/{filename}', function ($filename)
{
    $path = storage_path('app/public/' . $filename);

    if (!File::exists($path)) {
        abort(404);
    }

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});
Auth::routes();
// verify not working!
Route::get('/verify/', ['uses' => '\App\Http\Controllers\Auth\RegisterController@showRegistrationForm', 'as' => 'verification.verify']);
Route::get('/register-social-media/{provider}', '\App\Http\Controllers\Auth\RegisterController@redirectToProvider');
Route::get('/register-social-media/{provider}/callback', '\App\Http\Controllers\Auth\RegisterController@handleProviderCallback');

Route::get('/register/', ['uses' => '\App\Http\Controllers\Auth\RegisterController@showRegistrationForm']);
Route::get('/register/{role}', ['uses' => '\App\Http\Controllers\Auth\RegisterController@index']);
Route::post('/register/member', ['uses' => '\App\Http\Controllers\Auth\RegisterController@register_member']);
Route::post('/register/beneficiary', ['uses' => '\App\Http\Controllers\Auth\RegisterController@register_beneficiary']);
Route::post('/register/uploadHands', ['uses' => '\App\Http\Controllers\Auth\RegisterController@upload_hands_pictures']);
Route::get('/', ['uses' => 'HomeController@index', 'as' => 'app.home.index']);
Route::get('/contact-us', ['uses' => 'HomeController@contact', 'as' => 'app.home.contact']);
Route::post('/contact-us', ['uses' => 'HomeController@post_contact', 'as' => 'app.home.contact']);
Route::get('/terms', ['uses' => 'HomeController@terms', 'as' => 'app.home.term']);
Route::get('/privacy', ['uses' => 'HomeController@privacy', 'as' => 'app.home.privacy']);
Route::get('/about', ['uses' => 'HomeController@about', 'as' => 'app.home.about']);
Route::get('lang/{locale}', 'LocalizationController@index');

Route::post('/categories-requirements', ['uses' => 'CategoryController@getRequirements', 'as' => 'app.category.requirements']);
 Route::group(['middleware' => 're'], function () {
});
Route::group(['middleware' => 'auth'], function () {
    Route::get('/successful-payment', ['uses' => 'PaymentController@successful', 'as' => 'app.payment.successful']);    
    // Route::get('/failed-payment', ['uses' => 'PaymentController@failed', 'as' => 'app.payment.failed']);    
    
    Route::get('/user/settings', ['uses' => 'UserController@settings', 'as' => 'app.user.setting']);
    Route::post('/user/settings', ['uses' => 'UserController@post_setting', 'as' => 'app.user.setting']);

    Route::get('/set-category', ['uses' => 'UserController@set_category_get', 'as' => 'app.user.set_category']);
    Route::post('/set-category', ['uses' => 'UserController@set_category_post', 'as' => 'app.user.set_category']);
    Route::get('/user/dashboard', ['uses' => 'UserController@dashboard', 'as' => 'app.user.dashboard']);
    Route::get('/user/orders', ['uses' => 'UserController@orders', 'as' => 'app.user.order']);
    Route::get('/user/payments', ['uses' => 'UserController@payments', 'as' => 'app.user.payment']);
    Route::get('/user/bank', ['uses' => 'UserController@bank', 'as' => 'app.user.bank']);
    Route::get('/user/portofolios', ['uses' => 'UserController@portofolios', 'as' => 'app.user.portofolio']);
    Route::resource('/user', 'UserController', ['as' => 'app']);
    Route::resource('/order', 'OrderController', ['as' => 'app']);
    Route::get('/category/filter/', ['uses' => 'CategoryController@filter', 'as' => 'app.category.filter']);
    Route::resource('/category', 'CategoryController', ['as' => 'app']);
    Route::resource('/portofolio', 'PortofolioController', ['as' => 'app']);
    Route::resource('/payment', 'PaymentController', ['as' => 'app']);
});

app/Http/Controllers/Api/PortofolioController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\UserPortfolio;

class PortofolioController extends Controller
{
	/**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required|min:3|max:1000',
            'description' => 'nullable|min:3|max:5000',
            'url' => 'nullable|min:3|max:191|url',
            'attachment' => 'nullable|mimes:jpeg,png,jpg,gif,svg|max:2048'
        ]);

        if(request()->hasFile('attachment'))
        {
            request()->file('attachment')->store('public');
            $file = request()->file('attachment')->hashName();
            $attachment = \App\Models\Attachment::create(
                [
                    'name' => $file,
                    'orginal_name' => request()->file('attachment')->getClientOriginalName(),
                    'description' => $request->description,
                    'user_id' => $request->user('api')->id,
                    'type_id' => 5,
                    'model' => 'App\Models\UserPortfolio',
                    'model_id' => $request->user('api')->id
                ]
            );

            auth()->user()->attachments()->save($attachment);
        }

        $portfolio = UserPortfolio::create(array_merge($request->except('attachment'), ['user_id' => auth()->user()->id]));

		return response()->json([
            'data' => 'Portofolio Created Successfully.'
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    // public function update(UserPortfolio $portfolio, Request $request)
    // {
    //     return $request->all();
    //     $this->validate($request, [
    //         'title' => 'required|min:3|max:1000',
    //         'description' => 'nullable|min:3|max:5000',
    //         'url' => 'nullable|min:3|max:191|url',
    //         'attachment' => 'nullable|mimes:jpeg,png,jpg,gif,svg|max:2048'
    //     ]);

    //     if(request()->hasFile('attachment'))
    //     {
    //         request()->file('attachment')->store('public');
    //         $file = request()->file('attachment')->hashName();
    //         $attachment = \App\Models\Attachment::create(
    //             [
    //                 'name' => $file,
    //                 'orginal_name' => request()->file('attachment')->getClientOriginalName(),
    //                 'description' => $request->description,
    //                 'user_id' => $request->user('api')->id,
    //                 'type_id' => 5,
    //                 'model' => 'App\Models\UserPortfolio',
    //                 'model_id' => $request->user('api')->id
    //             ]
    //         );

    //         auth()->user()->attachments()->save($attachment);
    //     }

    //     $portfolio = UserPortfolio::update(array_merge($request->except('attachment'), ['user_id' => auth()->user()->id]));

	// 	return response()->json([
    //         'data' => 'Portofolio Created Successfully.'
    //     ]);
    // }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Balance  $balance
     * @return \Illuminate\Http\Response
     */
    public function destroy(UserPortfolio $portfolio, Request $request)
    {
        UserPortfolio::findOrFail($request->id)->delete();

        return response()->json([
            'data' => 'Portofolio Deleted Successfully.'
        ]);
    }
}

app/Http/Controllers/PortofolioController.php
<?php

namespace App\Http\Controllers;

use App\Models\UserPortfolio;
use Illuminate\Http\Request;

class PortofolioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = auth()->user();

        return view('app.portofolio.create', compact('user'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required|min:3|max:1000',
            'description' => 'nullable|min:3|max:5000',
            'url' => 'nullable|min:3|max:191|url',
            'attachment' => 'nullable|mimes:jpeg,png,jpg,gif,svg|max:2048'
        ]);

        if(request()->hasFile('attachment'))
        {
            request()->file('attachment')->store('public');
            $file = request()->file('attachment')->hashName();
            $attachment = \App\Models\Attachment::create(
                [
                    'name' => $file,
                    'orginal_name' => request()->file('attachment')->getClientOriginalName(),
                    'description' => $request->description,
                    'user_id' => auth()->user()->id,
                    'type_id' => 5,
                    'model' => 'App\Models\UserPortfolio',
                    'model_id' => auth()->user()->id
                ]
            );

            auth()->user()->attachments()->save($attachment);
        }

        $portfolio = UserPortfolio::create(array_merge($request->except('attachment'), ['user_id' => auth()->user()->id]));

        return redirect(route('app.user.portofolio'))->with('message', __('portofolio.success'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Balance  $balance
     * @return \Illuminate\Http\Response
     */
    public function show(Balance $balance)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Balance  $balance
     * @return \Illuminate\Http\Response
     */
    public function edit(Balance $balance)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Balance  $balance
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Balance $balance)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Balance  $balance
     * @return \Illuminate\Http\Response
     */
    public function destroy(UserPortfolio $portfolio)
    {
        return $portfolio->delete();
    }
}

resources/views/app/portofolio/create.blade.php
@extends('layouts.app')
@section('title')
إضافة عمل جديد
@endsection
@section('content')
    <div class="row">
        <div class="col-md-3">
            @include('partials.app.beneficiary_sidebar')
        </div>
        <div class="col-md-9">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-10">
                            <h4>إضافة عمل جديد</h4>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                <form method="post" action="{{ route('app.portofolio.store')}}" enctype="multipart/form-data">
                        @csrf
                        <div class="row">	
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label for="">عنوان العمل*</label>
                                    {!! Form::text('title', null, ['class' => 'form-control']) !!}
                                </div><!-- /.form-group -->
                            </div>
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label for="">وصف العمل</label>
                                    {!! Form::textarea('description', null, ['class' => 'form-control']) !!}
                                </div><!-- /.form-group -->
                            </div>
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label for="">رابط العمل*</label>
                                    {!! Form::text('url', null, ['class' => 'form-control']) !!}
                                </div><!-- /.form-group -->
                            </div>
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label for="">صورة للعمل*</label>
                                    {!! Form::file('attachment', null, ['class' => 'form-control']) !!}
                                </div><!-- /.form-group -->
                            </div>
                        </div>
                        <br>
                        <div class="center">
                            <a href="">
                                <button class="pricing-btn btn-block"  type="submit">حفظ</button>
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/app/portofolio/index.blade.php
@extends('layouts.app')
@section('title')
معرض اﻷعمال
@endsection
@section('content')
    <div class="row">
        <div class="col-md-3">
            @include('partials.app.beneficiary_sidebar')
        </div>
        <div class="col-md-9">
        <br>
            <h5><a href="{{ route('app.portofolio.create') }}"><i class="fa fa-plus"></i> أضف عمل جديد</a></h5>
            <br>
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-10">
                            <h4>معرض اﻷعمال</h4>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    
                    @if($portofolios->count() == 0)
                        <p>لا يوجد بيانات مضافه في الوقت الحالي</p>
                    @else
                    <table class="table">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>عنوان العمل</th>
                                <th>وصف العمل</th>
                                <th>رابط العمل</th>
                                <th>أدوات</th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach($portofolios as $portofolio)
                            <tr>
                                <td>{{ $portofolio->id }}#</td>
                                <td>{{ $portofolio->title }}</td>
                                <td>{{ $portofolio->description }}</td>
                                <td>
                                    @if(is_null($portofolio->url))
                                        -
                                    @else
                                        <a href="{{ $portofolio->url }}" target="_blank">عرض</a>
                                    @endif
                                </td>
                                <td>
                                    <a href="{{ route('app.portofolio.edit', $portofolio) }}" class="btn btn-info"><i class="fa fa-pencil-square-o"></i></a>
                                    <a href="{{ route('app.portofolio.show', $portofolio) }}" class="btn btn-danger"><i class="fa fa-trash"></i></a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    @endif
                </div>
            </div>
            <div class="text-center">
                {{ $portofolios->links() }}
            </div>
        </div>
    </div>
@endsection