routes/web.php
<?php
// Auth::logout();
Route::get('storage/{filename}', function ($filename)
{
    $path = storage_path('app/public/' . $filename);

    if (!File::exists($path)) {
        abort(404);
    }

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});
Auth::routes();
// verify not working!
Route::get('/verify/', ['uses' => '\App\Http\Controllers\Auth\RegisterController@showRegistrationForm', 'as' => 'verification.verify']);
Route::get('/register-social-media/{provider}', '\App\Http\Controllers\Auth\RegisterController@redirectToProvider');
Route::get('/register-social-media/{provider}/callback', '\App\Http\Controllers\Auth\RegisterController@handleProviderCallback');

Route::get('/register/', ['uses' => '\App\Http\Controllers\Auth\RegisterController@showRegistrationForm']);
Route::get('/register/{role}', ['uses' => '\App\Http\Controllers\Auth\RegisterController@index']);
Route::post('/register/member', ['uses' => '\App\Http\Controllers\Auth\RegisterController@register_member']);
Route::post('/register/beneficiary', ['uses' => '\App\Http\Controllers\Auth\RegisterController@register_beneficiary']);
Route::post('/register/uploadHands', ['uses' => '\App\Http\Controllers\Auth\RegisterController@upload_hands_pictures']);
Route::get('/', ['uses' => 'HomeController@index', 'as' => 'app.home.index']);
Route::get('/contact-us', ['uses' => 'HomeController@contact', 'as' => 'app.home.contact']);
Route::post('/contact-us', ['uses' => 'HomeController@post_contact', 'as' => 'app.home.contact']);
Route::get('/terms', ['uses' => 'HomeController@terms', 'as' => 'app.home.term']);
Route::get('/privacy', ['uses' => 'HomeController@privacy', 'as' => 'app.home.privacy']);
Route::get('/about', ['uses' => 'HomeController@about', 'as' => 'app.home.about']);
Route::get('lang/{locale}', 'LocalizationController@index');

Route::post('/categories-requirements', ['uses' => 'CategoryController@getRequirements', 'as' => 'app.category.requirements']);
 Route::group(['middleware' => 're'], function () {
});
Route::group(['middleware' => 'auth'], function () {
    Route::get('/successful-payment', ['uses' => 'PaymentController@successful', 'as' => 'app.payment.successful']);    
    // Route::get('/failed-payment', ['uses' => 'PaymentController@failed', 'as' => 'app.payment.failed']);    
    
    Route::get('/user/settings', ['uses' => 'UserController@settings', 'as' => 'app.user.setting']);
    Route::post('/user/settings', ['uses' => 'UserController@post_setting', 'as' => 'app.user.setting']);

    Route::get('/set-category', ['uses' => 'UserController@set_category_get', 'as' => 'app.user.set_category']);
    Route::post('/set-category', ['uses' => 'UserController@set_category_post', 'as' => 'app.user.set_category']);
    Route::get('/user/dashboard', ['uses' => 'UserController@dashboard', 'as' => 'app.user.dashboard']);
    Route::get('/user/orders', ['uses' => 'UserController@orders', 'as' => 'app.user.order']);
    Route::get('/user/payments', ['uses' => 'UserController@payments', 'as' => 'app.user.payment']);
    Route::get('/user/bank', ['uses' => 'UserController@bank', 'as' => 'app.user.bank']);
    Route::get('/user/portofolios', ['uses' => 'UserController@portofolios', 'as' => 'app.user.portofolio']);
    Route::resource('/user', 'UserController', ['as' => 'app']);
    Route::resource('/order', 'OrderController', ['as' => 'app']);
    Route::get('/category/filter/', ['uses' => 'CategoryController@filter', 'as' => 'app.category.filter']);
    Route::resource('/category', 'CategoryController', ['as' => 'app']);
    Route::resource('/portofolio', 'PortofolioController', ['as' => 'app']);
    Route::resource('/payment', 'PaymentController', ['as' => 'app']);
});

resources/views/partials/app/beneficiary_sidebar.blade.php
<div class="dashboard-sidebar">
    <div class="dashboard-user hidden-md-down">
        <div class="dashboard-user-image" style="background-image: url({{$user->avatar()}});">
        </div>
        <strong>{{ $user->fullName }}</strong>
    </div>
    <div class="dashboard-nav-primary">
        <ul class="nav nav-stacked">
            <li class="nav-item">
                <a href="{{ route('app.user.dashboard')}}" class="nav-link {{ \Request::segment(2) == 'dashboard' ? 'active' : '' }}">
                    <i class="fa fa-building"></i> {{ __('general.control_panel')}}
                </a>
            </li>

            <li class="nav-item">
                <a href="{{ route('app.user.order') }}" class="nav-link {{ \Request::segment(2) == 'orders' || \Request::segment(1) == 'order' ? 'active' : '' }}">
                    <i class="fa fa-suitcase"></i> {{ __('general.order')}}
                </a>
            </li>

            <li class="nav-item">
                <a href="{{ route('app.user.portofolio') }}" class="nav-link {{ \Request::segment(2) == 'portofolios' || \Request::segment(1) == 'portofolio' ? 'active' : '' }}">
                    <i class="fa fa-suitcase"></i> {{ __('general.protofolio')}}
                </a>
            </li>						

            <li class="nav-item">
                <a href="{{ route('app.user.payment') }}" class="nav-link {{ \Request::segment(2) == 'payments' || \Request::segment(1) == 'setting' ? 'active' : '' }}">
                    <i class="fa fa-globe"></i> {{ __('general.payment')}}
                </a>
            </li>

            <li class="nav-item">
                <a href="{{ route('app.user.setting') }}" class="nav-link {{ \Request::segment(2) == 'settings' || \Request::segment(1) == 'setting' ? 'active' : '' }}">
                    <i class="fa fa-users"></i> {{ __('general.setting')}}
                </a>
            </li>					
        </ul>
    </div><!-- /.dashboard-nav-primary -->

</div><!-- /.dashboard-sidebar -->

resources/views/partials/app/breadcrumb.blade.php
@if(! is_null(\Request::segment(1)))
<div class="content-title">
	<div class="content-title-inner">
		<div class="container">		
			<h1>@yield('title')</h1>		

			<ol class="breadcrumb">
				<li><a href="/">{{ __('general.home_page') }}</a></li>
				@if(\Route::has('app.'.\Request::segment(1).'.index'))
				<li><a href="#">{{ __('general.' . \Request::segment(1). '') }}</a></li>
				@endif
				<li><a href="">@yield('title')</a></li>
			</ol>			
		</div><!-- /.container -->
	</div><!-- /.content-title-inner -->
</div><!-- /.content-title -->
@endif

resources/views/partials/app/footer.blade.php
<div class="footer-wrapper">
	<div class="container">
		<div class="footer-inner">
			<div class="row footer-top">
				<div class="col-md-6 ">
					<h2>{{ __('general.social_account')}}</h2>

					<div class="social">
						<a href="{{ $app_setting->facebook }}" targe="_blank"><i class="fa fa-facebook"></i></a>
						<a href="{{ $app_setting->twitter }}" targe="_blank"><i class="fa fa-twitter"></i></a>
						<!-- <a href="{{ $app_setting->snapchat }}" targe="_blank"><i class="fa fa-snapchat"></i></a> -->
						<a href="{{ $app_setting->instagram }}" targe="_blank"><i class="fa fa-instagram"></i></a>
					</div><!-- /.social -->									
				</div><!-- /.footer-top-left -->

				<div class="col-md-6 ">
					<h2>{{ $app_setting->website_title }}</h2>

					<p>
						{{ $app_setting->about }}
					</p>					
				</div><!-- /.footer-top-right -->
			</div><!-- /.footer-top -->

			<div class="footer-bottom">
				<div class="footer-left">
					&copy; {{ __('general.copyright')}} {{ $app_setting->website_title }} {{ date('Y') }}
				</div><!-- /.footer-left -->

				<div class="footer-right">
					<ul class="nav nav-pills">
						<li class="nav-item"><a href="{{ route('app.home.term') }}" class="nav-link">{{ __('general.terms')}}</a></li>
						<li class="nav-item"><a href="{{ route('app.home.privacy') }}" class="nav-link">{{ __('general.privacy')}}</a></li>
						<li class="nav-item"><a href="{{ route('app.home.contact') }}" class="nav-link">{{ __('general.contact_us')}}</a></li>
					</ul>
				</div><!-- /.footer-right -->			
			</div><!-- /.footer-bottom -->
		</div><!-- /.footer-inner -->
	</div><!-- /.container -->
</div><!-- /.footer-wrapper -->

resources/views/partials/app/header.blade.php
<div class="header-wrapper">
	<div class="header header-small">
		<div class="header-inner">
			<div class="container">
                <div class="header-topbar">
					<div class="header-topbar-right">
						<ul class="nav nav-pills nav-topbar">

                            @if(config('app.locale') == 'ar')
                            <li class="nav-item ">
                                <a href="/lang/en" class="nav-link ">
                                    English
                                </a>
                            </li>
                            @elseif(config('app.locale') == 'en')
                            <li class="nav-item ">
                                <a href="/lang/ar" class="nav-link ">
                                    عربي
                                </a>
                            </li>
                            @endif
						</ul><!-- /.nav -->
					</div><!-- /.header-topbar-left -->

					<div class="header-topbar-left nav-topbar nav-topbar-social">
						<ul class="nav nav-pills">
							<li class="nav-item"><a href="{{ $app_setting->facebook }}" class="nav-link"><i class="fa fa-facebook"></i></a></li>
							<li class="nav-item"><a href="{{ $app_setting->twitter }}" class="nav-link"><i class="fa fa-twitter"></i></a></li>
							<li class="nav-item"><a href="{{ $app_setting->instagram }}" class="nav-link"><i class="fa fa-instagram"></i></a></li>
                        </ul><!-- /.nav -->
					</div><!-- /.header-topbar-right -->
				</div>
				<div class="header-top">
					<div class="header-top-inner">
						<a class="header-logo" href="{{ url('/') }}">
							<span class="header-logo-shape"></span>
							<span class="header-logo-text"></span>
						</a><!-- /.header-logo -->


<div class="nav-primary-wrapper collapse navbar-toggleable-sm">
        <ul class="nav nav-pills nav-primary">
                <li class="nav-item">
                    <a href="/" class="nav-link {{ \Request::segment(1) == '/' ? 'active' : '' }}">
                        {{ __('general.home_page')}}
                    </a>
                </li>

                @if(auth()->user() && auth()->user()->hasRole('admin'))
                <li class="nav-item nav-item-parent">
                    <a href="#" class="nav-link ">
                        {{ __('general.profile' )}}
                    </a>
                    <ul class="sub-menu">
                        <li><a href="{{ url('/nova') }}">{{ __('general.control_panel' )}}</a></li>
                        <li><a href="{{ route('app.user.show', auth()->user())}}">{{ __('general.setting' )}}</a></li>
                        <li><a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('frm-logout').submit();">{{ __('general.logout' )}}</a></li>
                        <form id="frm-logout" action="{{ route('logout') }}" method="POST" style="display: none;">
                            {{ csrf_field() }}
                        </form>
                    </ul>
                </li>
                @endif

                @if(auth()->user() && auth()->user()->hasRole('member'))
                <li class="nav-item nav-item-parent">
                    <a href="#" class="nav-link ">
                        حسابي الشخصي
                    </a>
                    <ul class="sub-menu">
                        <li><a href="{{ route('app.user.dashboard')}}">{{ __('general.control_panel' )}}</a></li>
                        <li><a href="{{ route('app.user.order')}}">{{ __('general.order' )}}</a></li>
                        <li><a href="{{ route('app.user.payment')}}">{{ __('general.payment' )}}</a></li>
                        <li><a href="{{ route('app.user.setting')}}">{{ __('general.setting' )}}</a></li>
                        <li><a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('frm-logout').submit();">{{ __('general.logout' )}}</a></li>
                        <form id="frm-logout" action="{{ route('logout') }}" method="POST" style="display: none;">
                            {{ csrf_field() }}
                        </form>
                    </ul>
                </li>
                @endif

                @if(auth()->user() && auth()->user()->hasRole('beneficiary'))
                <li class="nav-item nav-item-parent">
                    <a href="#" class="nav-link ">
                        {{ __('general.profile' )}}
                    </a>
                    <ul class="sub-menu">
                        <li><a href="{{ route('app.user.dashboard')}}">{{ __('general.control_panel' )}}</a></li>
                        <li><a href="{{ route('app.user.show', auth()->user())}}">{{ __('general.myprofile' )}}</a></li>
                        <li><a href="{{ route('app.user.portofolio')}}">{{ __('general.protofolio' )}}</a></li>
                        <li><a href="{{ route('app.user.payment')}}">{{ __('general.payment' )}}</a></li>
                        <li><a href="{{ route('app.user.setting')}}">{{ __('general.setting' )}}</a></li>
                        <li><a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('frm-logout').submit();">{{ __('general.logout' )}}</a></li>
                        <form id="frm-logout" action="{{ route('logout') }}" method="POST" style="display: none;">
                            {{ csrf_field() }}
                        </form>
                    </ul>
                </li>
                @endif

                <li class="nav-item nav-item-parent">
                    <a href="#" class="nav-link ">
                        {{ __('general.service_menu' )}}
                    </a>

                    <ul class="sub-menu">
                        @foreach($menu as $parent)
                            @if(is_null($parent->parent) && $parent->children->count() == 0)
                            <li><a href="{{ route('app.category.show', $parent->category) }}">{{ $parent->name }}</a></li>
                            @elseif($parent->children->count() > 0)
                            <li class="nav-item-parent">
                                <a href="#" class="nav-link ">
                                {{ $parent->name }}
                                </a>
                                <ul class="sub-menu">
                                    @foreach($parent->children as $child)
                                    <li><a href="{{ route('app.category.show', $child->category) }}">{{ $child->name }}</a></li>
                                    @endforeach
                                </ul>
                            </li>
                            @endif
                        @endforeach
                    </ul>
                </li>
                @if(auth()->guest())
                <li class="nav-item ">
                    <a href="/login" class="nav-link ">
                        {{ __('general.login' )}}
                    </a>
                </li>
                <li class="nav-item ">
                    <a href="/register" class="nav-link ">
                        {{ __('general.register' )}}
                    </a>
                </li>
                @endif
                <li class="nav-item ">
                    <a href="{{ route('app.home.about') }}" class="nav-link ">
                        {{ __('general.about_us' )}}
                    </a>
                </li>
                <li class="nav-item ">
                    <a href="{{ route('app.home.contact') }}" class="nav-link ">
                        {{ __('general.contact_us' )}}
                    </a>
                </li>

</ul></div><!-- /.nav-primary -->


						<button class="navbar-toggler pull-xs-right hidden-md-up" type="button" data-toggle="collapse" data-target=".nav-primary-wrapper">
	                        <span></span>
	                        <span></span>
	                        <span></span>
	                    </button>
					</div><!-- /.header-top-inner -->
				</div><!-- /.header-top -->
			</div><!-- /.container -->
		</div><!-- /.header-inner -->
	</div><!-- /.header -->
</div>

resources/views/partials/app/member_sidebar.blade.php
<div class="dashboard-sidebar">
    <div class="dashboard-user hidden-md-down">
        <div class="dashboard-user-image" style="background-image: url({{$user->avatar()}});">
        </div>
        <strong>{{ $user->fullName }}</strong>
    </div>
    <div class="dashboard-nav-primary">
        <ul class="nav nav-stacked">
            <li class="nav-item">
                <a href="{{ route('app.user.dashboard')}}" class="nav-link {{ \Request::segment(2) == 'dashboard' ? 'active' : '' }}">
                    <i class="fa fa-building"></i> {{ __('general.control_panel')}}
                </a>
            </li>

            <li class="nav-item">
                <a href="{{ route('app.user.order') }}" class="nav-link {{ \Request::segment(2) == 'orders' || \Request::segment(1) == 'order' ? 'active' : '' }}">
                    <i class="fa fa-suitcase"></i> {{ __('general.order')}}
                </a>
            </li>

            <li class="nav-item">
                <a href="{{ route('app.user.payment') }}" class="nav-link {{ \Request::segment(2) == 'payments' || \Request::segment(1) == 'setting' ? 'active' : '' }}">
                    <i class="fa fa-globe"></i> {{ __('general.payment')}}
                </a>
            </li>

            <li class="nav-item">
                <a href="{{ route('app.user.setting') }}" class="nav-link {{ \Request::segment(2) == 'settings' || \Request::segment(1) == 'setting' ? 'active' : '' }}">
                    <i class="fa fa-users"></i> {{ __('general.setting')}}
                </a>
            </li>					
        </ul>
    </div><!-- /.dashboard-nav-primary -->

</div><!-- /.dashboard-sidebar -->

resources/views/partials/app/messages.blade.php
@if ($errors->any())
    <div class="alert alert-danger " role="alert">
        <ul class="list-group">
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
@if(session('message'))
<div class="alert alert-success" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    </button>
    <strong>{{ session('message') }}</strong>
</div>
@endif

resources/views/partials/app/sidefilter.blade.php
<div class="filter filter-secondary checkbox-light">
    
    {!! Form::model($model, ['route' => 'app.category.filter', 'method' => 'get']) !!}
        <div class="form-group">
            @php $all = [null => 'All']; @endphp
            <label>{{ __('general.category')}}</label>
            {!! Form::select('category_id', $categories, null, ['class' => 'form-control']) !!}
        </div><!-- /.form-group -->

        <div class="form-group">
            <label>{{ __('general.country')}}</label>
            {!! Form::select('country_id', $all + $countries->toArray(), null, ['class' => 'form-control']) !!}
        </div><!-- /.form-group -->

        <div class="form-group">
            <label>{{ __('general.city')}}</label>
            {!! Form::text('city', null, ['class' => 'form-control']) !!}
        </div><!-- /.form-group -->

        <div class="form-group">
            <label>{{ __('general.gender')}}</label>
            {!! Form::select('gender_id', $all + $genders->toArray(), null, ['class' => 'form-control']) !!}
        </div><!-- /.form-group -->

        <div class="form-group">
            <label>{{ __('general.rate')}}</label>
            {!! Form::select('rate_id', $all + $rates->toArray(), null, ['class' => 'form-control']) !!}
        </div><!-- /.form-group -->

        <div class="form-group">
            <label>{{ __('general.skin_color')}}</label>
            {!! Form::select('skin_color', $all + $skin_colors->toArray(), null, ['class' => 'form-control']) !!}
        </div><!-- /.form-group -->

        <div class="form-group">
            <label>{{ __('general.eye_color')}}</label>
            {!! Form::select('eye_color', array_merge([null => 'All'], $eye_colors->toArray()), null, ['class' => 'form-control']) !!}
        </div><!-- /.form-group -->

        <div class="form-group">
            <label>{{ __('general.hair_color')}}</label>
            {!! Form::select('hair_color', $all + $hair_colors->toArray(), null, ['class' => 'form-control']) !!}
        </div><!-- /.form-group -->

        <div class="row">
            <div class="form-group col-xl-6">
                <label>{{ __('general.height_from')}}</label>
                {!! Form::text('height_from', null, ['class' => 'form-control']) !!}
            </div><!-- /.form-group -->

            <div class="form-group col-xl-6">
                <label>{{ __('general.to')}}</label>
                {!! Form::text('height_to', null, ['class' => 'form-control']) !!}
            </div><!-- /.form-group -->

            <div class="form-group col-xl-6">
                <label>{{ __('general.weight_from')}}</label>
                {!! Form::text('weight_from', null, ['class' => 'form-control']) !!}
            </div><!-- /.form-group -->

            <div class="form-group col-xl-6">
                <label>{{ __('general.to')}}</label>
                {!! Form::text('weight_to', null, ['class' => 'form-control']) !!}
            </div><!-- /.form-group -->

            <div class="form-group col-xl-6">
                <label>{{ __('general.age_from')}}</label>
                {!! Form::text('age_from', null, ['class' => 'form-control']) !!}
            </div><!-- /.form-group -->

            <div class="form-group col-xl-6">
                <label>{{ __('general.to')}}</label>
                {!! Form::text('age_to', null, ['class' => 'form-control']) !!}
            </div><!-- /.form-group -->

            <div class="form-group col-xl-6">
                <label>{{ __('general.price_from')}}</label>
                {!! Form::text('price_from', null, ['class' => 'form-control']) !!}
            </div><!-- /.form-group -->

            <div class="form-group col-xl-6">
                <label>{{ __('general.to')}}</label>
                {!! Form::text('price_to', null, ['class' => 'form-control']) !!}
            </div><!-- /.form-group -->		
        </div><!-- /.row -->

        <h2>{{ __('general.can_travel')}}</h2>

        <div class="checkbox">
            <label><div class="ez-radio">
                {!! Form::radio('is_travel', 1, null, ['class' => 'ez-hide']) !!}
            </div>
                <!-- <input type="radio" name="is_travel" value="1" class="ez-hide"></div>  -->
            {{ __('general.yes')}}</label>				
        </div><!-- /.checkbox -->

        <div class="checkbox">
            <label><div class="ez-radio">
                {!! Form::radio('is_travel', 0, null, ['class' => 'ez-hide']) !!}</div> 
            {{ __('general.no')}}</label>				
        </div><!-- /.checkbox -->

        <div class="checkbox">
            <label><div class="ez-radio">
                {!! Form::radio('is_travel', null, null, ['class' => 'ez-hide']) !!}
            </div> 
            {{ __('general.notcare')}}</label>
        </div><!-- /.checkbox -->

        <div class="form-group-btn form-group-btn-placeholder-gap">
            <button type="submit" class="btn btn-orange btn-block">{{ __('general.search')}}</button>
        </div><!-- /.form-group -->		
    </form>
</div><!-- /.filter -->	