routes/web.php
<?php
// Auth::logout();
Route::get('storage/{filename}', function ($filename)
{
    $path = storage_path('app/public/' . $filename);

    if (!File::exists($path)) {
        abort(404);
    }

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});
Auth::routes();
// verify not working!
Route::get('/verify/', ['uses' => '\App\Http\Controllers\Auth\RegisterController@showRegistrationForm', 'as' => 'verification.verify']);
Route::get('/register-social-media/{provider}', '\App\Http\Controllers\Auth\RegisterController@redirectToProvider');
Route::get('/register-social-media/{provider}/callback', '\App\Http\Controllers\Auth\RegisterController@handleProviderCallback');

Route::get('/register/', ['uses' => '\App\Http\Controllers\Auth\RegisterController@showRegistrationForm']);
Route::get('/register/{role}', ['uses' => '\App\Http\Controllers\Auth\RegisterController@index']);
Route::post('/register/member', ['uses' => '\App\Http\Controllers\Auth\RegisterController@register_member']);
Route::post('/register/beneficiary', ['uses' => '\App\Http\Controllers\Auth\RegisterController@register_beneficiary']);
Route::post('/register/uploadHands', ['uses' => '\App\Http\Controllers\Auth\RegisterController@upload_hands_pictures']);
Route::get('/', ['uses' => 'HomeController@index', 'as' => 'app.home.index']);
Route::get('/contact-us', ['uses' => 'HomeController@contact', 'as' => 'app.home.contact']);
Route::post('/contact-us', ['uses' => 'HomeController@post_contact', 'as' => 'app.home.contact']);
Route::get('/terms', ['uses' => 'HomeController@terms', 'as' => 'app.home.term']);
Route::get('/privacy', ['uses' => 'HomeController@privacy', 'as' => 'app.home.privacy']);
Route::get('/about', ['uses' => 'HomeController@about', 'as' => 'app.home.about']);
Route::get('lang/{locale}', 'LocalizationController@index');

Route::post('/categories-requirements', ['uses' => 'CategoryController@getRequirements', 'as' => 'app.category.requirements']);
 Route::group(['middleware' => 're'], function () {
});
Route::group(['middleware' => 'auth'], function () {
    Route::get('/successful-payment', ['uses' => 'PaymentController@successful', 'as' => 'app.payment.successful']);    
    // Route::get('/failed-payment', ['uses' => 'PaymentController@failed', 'as' => 'app.payment.failed']);    
    
    Route::get('/user/settings', ['uses' => 'UserController@settings', 'as' => 'app.user.setting']);
    Route::post('/user/settings', ['uses' => 'UserController@post_setting', 'as' => 'app.user.setting']);

    Route::get('/set-category', ['uses' => 'UserController@set_category_get', 'as' => 'app.user.set_category']);
    Route::post('/set-category', ['uses' => 'UserController@set_category_post', 'as' => 'app.user.set_category']);
    Route::get('/user/dashboard', ['uses' => 'UserController@dashboard', 'as' => 'app.user.dashboard']);
    Route::get('/user/orders', ['uses' => 'UserController@orders', 'as' => 'app.user.order']);
    Route::get('/user/payments', ['uses' => 'UserController@payments', 'as' => 'app.user.payment']);
    Route::get('/user/bank', ['uses' => 'UserController@bank', 'as' => 'app.user.bank']);
    Route::get('/user/portofolios', ['uses' => 'UserController@portofolios', 'as' => 'app.user.portofolio']);
    Route::resource('/user', 'UserController', ['as' => 'app']);
    Route::resource('/order', 'OrderController', ['as' => 'app']);
    Route::get('/category/filter/', ['uses' => 'CategoryController@filter', 'as' => 'app.category.filter']);
    Route::resource('/category', 'CategoryController', ['as' => 'app']);
    Route::resource('/portofolio', 'PortofolioController', ['as' => 'app']);
    Route::resource('/payment', 'PaymentController', ['as' => 'app']);
});

app/Http/Controllers/Api/UserController.php
<?php

namespace App\Http\Controllers\Api;

use App\Models\User;
use App\Models\Order;
use App\Models\UserPortfolio;
use App\Models\Payment;
use App\Models\Balance;
use App\Models\Category;
use App\Models\SocialMedia;
use Spatie\Permission\Models\Role;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;
use MediaEmbed\MediaEmbed;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request)
    {
        $user = User::find($request->user_id);
        if($user->hasRole('beneficiary'))
        {
            $similar_users = User::where('id', '!=', $user->id)
            ->where('user_category_id', $user->category->id)
            ->inRandomOrder()
            ->limit(3)
            ->get();

			return response()->json([
                'user' => $user,
				'similar_users' => $similar_users
			]);
        }

		return response()->json([
            'user' => $user,
			'similar_users' => []
		]);
    }

    public function dashboard(Request $request)
    {
        $user = $request->user('api');

        $orders = Order::where('user_id', $user->id)->latest()->limit(5)->get();
        $payments = Payment::where('user_id', $user->id)->latest()->limit(5)->get();

        $order_count = Order::where('beneficiary_id', $user->id)->count();
        if(Balance::where('user_id', $user->id)->first() != null)
        {
            $payment_count = Balance::where('user_id', $user->id)->first()->balance;
        }
        else
        {
            $payment_count = null;
        }


        $portofolio_count = UserPortfolio::where('user_id', $user->id)->count();

		return response()->json([
			'orders' => $orders,
			'payments' => $payments,
			'order_count' => $order_count,
			'payment_count' => $payment_count,
			'portofolio_count' => $portofolio_count
		]);
    }

    public function post_setting(Request $request)
    {
        $data = $request->toArray();
        $user = $request->user('api');

        $validations = [
            'fname' => ['required', 'string', 'max:255'],
            'lname' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users,email,'. $user->id],
            'password' => ['nullable', 'string', 'min:6', 'confirmed'],
            'phone' => ['required', 'string', 'min:6', 'max:20'],
            'country_id' => 'required|integer|exists:countries,id',
            'user_gender_id' => 'required|integer|exists:user_genders,id',
            'is_travel' => 'nullable|integer',
            'city' => 'required|max:255',
            'about' => 'required|max:4000|min:10',
            'facebook' => 'nullable|max:4000|min:3',
            'twitter' => 'nullable|max:4000|min:3',
            'instagram' => 'nullable|max:4000|min:3',
            'snapchat' => 'nullable|max:4000|min:3',
            'residence_country_id' => 'required|integer|exists:countries,id'
        ];

        if(! is_null($user->user_category_id))
        {
            $requirements = Category::find($user->user_category_id)->requirements;

            if($requirements->count() > 0)
            {
                foreach($requirements as $requirement)
                {
                    $validations = array_merge($validations, $requirement->validations);
                }
            }
        }

        // if register with social, there is no password so it will require it.
        if(is_null($user->password))
        {
            $validations = array_merge($validations, ['password' => ['required', 'string', 'min:6', 'confirmed']]);
        }

        if(is_null($user->user_category_id))
        {
            $validations = array_merge($validations, ['user_category_id' => 'required|integer|exists:categories,id']);
        }

        $this->validate($request, $validations);

        if(isset($data['password']) && ! is_null($data['password']))
        {
            // $data['password'] = Hash::make($data['password']);
            $user->update(['password' => Hash::make($data['password'])]);
        }

        // if user is bene
        if($user->hasRole('beneficiary'))
        {
            // if there is introduction video, we need to conver it to embed url.
            if(isset($data['video']) && ! is_null($data['video']))
            {
                $MediaEmbed = new MediaEmbed();
                if(is_null($MediaEmbed->parseUrl($data['video'])))
                {
                    return back()->with('message', 'يبدو أن رابط الفيديو غير صحيح، من فضلك تأكد أن الرابط يحتوي على فيديو.');
                }
                $data['embed_video'] = $MediaEmbed->parseUrl($data['video'])->getEmbedCode();
                $user->update(['video' => $data['video'], 'embed_video' => $data['embed_video']]);
            }

            if(isset($data['user_category_id']) && ! is_null($data['user_category_id']))
            {
                $user->update(['user_category_id' => $data['user_category_id']]);
            }

            if(isset($data['height']) && ! is_null($data['height']))
            {
                $user->update(['height' => $data['height'], 'weight' => $data['weight'], 'age' => $data['age']]);
            }

            if(isset($data['eye_color_id']) && ! is_null($data['eye_color_id']))
            {
                $user->update(['eye_color_id' => $data['eye_color_id']]);
            }

            if(isset($data['hair_color_id']) && ! is_null($data['hair_color_id']))
            {
                $user->update(['hair_color_id' => $data['hair_color_id']]);
            }

            if(isset($data['skin_color_id']) && ! is_null($data['skin_color_id']))
            {
                $user->update(['skin_color_id' => $data['skin_color_id']]);
            }

            if(isset($data['is_travel']) && ! is_null($data['is_travel']))
            {
                $user->update(['is_travel' => $data['is_travel']]);
            }

            $user->update([
                // 'user_category_id' => $data['user_category_id'],
                'fname' => $data['fname'],
                'lname' => $data['lname'],
                'email' => $data['email'],
                'phone' => $data['phone'],
                'about' => $data['about'],
                'city' => $data['city'],
                'country_id' => $data['country_id'],
                'user_gender_id' => $data['user_gender_id'],
                'residence_country_id' => $data['residence_country_id'],
            ]);

            $this->storePrice($data, $user);
            $this->storeSocialMedia($data, $user);
            $this->storeAccents($data, $user);
        }
        else if($user->hasRole('member'))
        {
            $user->update([
                // 'user_category_id' => $data['user_category_id'],
                'fname' => $data['fname'],
                'lname' => $data['lname'],
                'email' => $data['email'],
                'phone' => $data['phone'],
                'about' => $data['about'],
                'city' => $data['city'],
                'country_id' => $data['country_id'],
                'user_gender_id' => $data['user_gender_id'],
                'residence_country_id' => $data['residence_country_id'],
            ]);
        }

        $this->handleUploads($data, $user);

		return response()->json([
			'message' => 'User settings updated successfully.',
		]);
    }

    public function payments(Request $request)
    {
        $user = $request->user('api');
        $payments = Payment::where('user_id', $user->id)->paginate(10);

		return response()->json([
			'payments' => $payments,
		]);
    }

    public function portofolios(Request $request)
    {
        $user = $request->user('api');
        $portofolios = UserPortfolio::where('user_id', $user->id)->paginate(10);

		return response()->json([
			'portofolios' => $portofolios,
		]);
    }

    public function orders(Request $request)
    {
        $user = $request->user('api');
        $orders = Order::where('user_id', $user->id)->orWhere('beneficiary_id', $user->id)->paginate(10);

        return response()->json([
			'orders' => $orders,
		]);
    }

    private function storeSocialMedia($data, $user)
    {
        if(isset($data['facebook']) && ! is_null($data['facebook']))
        {
            $facebook = SocialMedia::where('english_name', 'facebook')->first();
            $user->socials()->sync([$facebook->id => ['url' => $data['facebook']]], false);
        }
        else
        {
            $facebook = SocialMedia::where('english_name', 'facebook')->first();
            $user->socials()->detach($facebook);
        }

        if(isset($data['instagram']) && ! is_null($data['instagram']))
        {
            $instagram = SocialMedia::where('english_name', 'instagram')->first();
            $user->socials()->sync([$instagram->id => ['url' => $data['instagram']]], false);
        }
        else
        {
            $instagram = SocialMedia::where('english_name', 'instagram')->first();
            $user->socials()->detach($instagram);
        }

        if(isset($data['twitter']) && ! is_null($data['twitter']))
        {
            $twitter = SocialMedia::where('english_name', 'twitter')->first();
            $user->socials()->sync([$twitter->id => ['url' => $data['twitter']]], false);

resources/views/app/user/dashboard/show.blade.php
@extends('layouts.app')
@section('title')
{{ __('general.control_panel')}}
@endsection
@section('content')
    <div class="row">
        <div class="col-md-3">
            @include('partials.app.'. $user->roles()->first()->name .'_sidebar')
        </div>
        <div class="col-md-9">
            <!-- boxes -->
            @if($user->hasRole('beneficiary'))
            <div class="row">
                <div class="col-md-4">
                    <div class="dash-box dash-box-color-1">
                        <div class="dash-box-icon">
                            <i class="fa fa-money"></i>
                        </div>
                        <div class="dash-box-body">
                            <span class="dash-box-count">{{ $payment_count->balance }} {{ __('general.ryial')}}</span>
                            <span class="dash-box-title">{{ __('general.balance')}}</span>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="dash-box dash-box-color-2">
                        <div class="dash-box-icon">
                            <i class="fa fa-suitcase"></i>
                        </div>
                        <div class="dash-box-body">
                            <span class="dash-box-count">{{ $order_count }}</span>
                            <span class="dash-box-title">{{ __('general.order_count')}}</span>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="dash-box dash-box-color-3">
                        <div class="dash-box-icon">
                            <i class="fa fa-briefcase"></i>
                        </div>
                        <div class="dash-box-body">
                            <span class="dash-box-count">{{ $portofolio_count }}</span>
                            <span class="dash-box-title">{{ __('general.portofolio_count')}}</span>
                        </div>
                    </div>
                </div>
            </div>
            @endif
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-10">
                            <h4>{{ __('general.last_orders')}}</h4>
                        </div>
                        <div class="col-md-2 text-right">
                            <a href="{{ route('app.user.order') }}"><p>{{ __('general.show_all')}}</p></a>
                        </div>
                    </div>
                </div>
                <div class="card-body">

                    @if($orders->count() == 0)
                        <p>{{ __('general.no_result')}}</p>
                    @else
                    <table class="table">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>{{ __('general.order_status')}}</th>
                                <th>{{ __('general.price')}}</th>
                                <th>{{ __('general.show')}}</th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach($orders as $order)
                            <tr>
                                <td>#{{ $order->id }}</td>
                                <td>{{ $order->status()->first()->name }}</td>
                                <td>{{ is_null($order->price) ? __('general.under_pricing') : $order->price .__('general.ryial') }}</td>
                                <td>
                                    <a href="{{ route('app.order.show', $order) }}" class="btn btn-primary"><i class="fa fa-eye"></i></a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    @endif
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-10">
                            <h4>{{ __('general.last_payment')}}</h4>
                        </div>
                        <div class="col-md-2 text-right">
                            <a href="{{ route('app.user.payment') }}"><p>{{ __('general.show_all')}}</p></a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    @if($payments->count() == 0)
                        <p>{{ __('general.no_result')}}</p>
                    @else
                    <table class="table">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>{{ __('general.payment_code')}}</th>
                                <th>{{ __('general.order')}}</th>
                                <th>{{ __('general.amount')}}</th>
                                <th>{{ __('general.status')}}</th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach($payments as $payment)
                            <tr>
                                <td>#{{ $payment->id }}</td>
                                <td>{{ $payment->payment_code }}</td>
                                <td>{{ $payment->order->id }}</td>
                                <td>{{ $payment->amount }}</td>
                                <td>{{ $payment->status->name }}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection